services:
  app:
    image: gradle:8.5-jdk17
    working_dir: /app
    command: [ "gradle", "bootRun", "--no-daemon" ] # --debug
    volumes:
        - .:/app
    ports:
      - "8081:8080"
    networks:
      - 'spring-boot-local'
    environment:
#      APP
      JWT_EXPIRATION_IN_MINUTES: '${JWT_EXPIRATION_IN_MINUTES}'
      JWT_SECRET: '${JWT_SECRET}'
#      DB
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      FORWARD_DB_PORT: '${FORWARD_DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
#      DB_TEST
      DB_TEST_HOST: '${DB_TEST_HOST}'
      DB_TEST_PORT: '${DB_TEST_PORT}'
      FORWARD_DB_TEST_PORT: '${FORWARD_DB_TEST_PORT}'
      DB_TEST_DATABASE: '${DB_TEST_DATABASE}'
      DB_TEST_USERNAME: '${DB_TEST_USERNAME}'
      DB_TEST_PASSWORD: '${DB_TEST_PASSWORD}'
#      REDIS
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
#      SPRING_PROFILES_ACTIVE: Local
    depends_on:
      - pgsql
      - redis
      - pgsql-test
  pgsql:
    image: postgres:17
    ports:
      - '${FORWARD_DB_PORT:-5432}:${DB_PORT}'
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'pgsql-data-local:/var/lib/postgresql/data'
    networks:
      - 'spring-boot-local'
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}']
      retries: 3
      timeout: 5s
  pgsql-test:
    image: postgres:17
    ports:
      - '${FORWARD_DB_TEST_PORT:-5433}:${DB_TEST_PORT}'
    environment:
      PGPASSWORD: '${DB_TEST_PASSWORD}'
      POSTGRES_DB: '${DB_TEST_DATABASE}'
      POSTGRES_USER: '${DB_TEST_USERNAME}'
      POSTGRES_PASSWORD: '${DB_TEST_PASSWORD}'
    volumes:
      - 'pgsql-data-test:/var/lib/postgresql/data'
    networks:
      - 'spring-boot-local'
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-q', '-d', '${DB_TEST_DATABASE}', '-U', '${DB_TEST_USERNAME}' ]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    command: [ 'redis-server', '--requirepass', '${REDIS_PASSWORD}' ]
    volumes:
      - 'redis-data-local:/data'
    networks:
      - 'spring-boot-local'
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      retries: 3
      timeout: 5s
networks:
  spring-boot-local:
    driver: bridge
volumes:
  pgsql-data-local:
    driver: local
  pgsql-data-test:
    driver: local
  redis-data-local:
    driver: local
