server:
  port: 8080
spring:
  flyway:
    baseline-on-migrate: true
  cache:
    type: redis
    cache-names: runtimes
    redis:
      time-to-live: 60000
      cache-null-values: false
      use-key-prefix: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${FORWARD_DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
client-url: http://localhost:8886/submission-test-result
app:
  jwtExpirationInMinutes: ${JWT_EXPIRATION_IN_MINUTES}
  jwtSecret: ${JWT_SECRET}