# Server Configuration
server:
  port: ${SERVER_PORT:8080}

# Spring Configuration
spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:autograder}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  # Database Migration Configuration
  flyway:
    baselineOnMigrate: true

  # JPA Configuration  
  jpa:
    database: postgresql
    showSql: ${SHOW_SQL:true}
    hibernate:
      ddlAuto: validate
    openInView: true

  # Redis Cache Configuration
  cache:
    type: redis
    cacheNames: runtimes
    redis:
      timeToLive: ${CACHE_TTL:60000}
      cacheNullValues: false
      useKeyPrefix: true
  
  # Redis Connection Configuration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

# Application-specific Configuration
app:
  security:
    jwt:
      expirationMinutes: ${JWT_EXPIRATION:60}
      secret: ${JWT_SECRET}
  client:
    enabled: ${CLIENT_ENABLED}
    submissionResultUrl: ${CLIENT_URL}

# Actuator
management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
